;;;; src/crypto/aes.lisp — AES-256-CBC encryption (FIPS 197)
;;;; Full implementation: key expansion, encrypt/decrypt blocks, CBC mode, PKCS7 padding.
;;;; No external dependencies. Pure Common Lisp on SBCL.
(in-package :cauldron.crypto)

;;; ---------- AES S-box (FIPS 197, Section 5.1.1) ----------

(defvar +aes-sbox+
  #(#x63 #x7c #x77 #x7b #xf2 #x6b #x6f #xc5 #x30 #x01 #x67 #x2b #xfe #xd7 #xab #x76
    #xca #x82 #xc9 #x7d #xfa #x59 #x47 #xf0 #xad #xd4 #xa2 #xaf #x9c #xa4 #x72 #xc0
    #xb7 #xfd #x93 #x26 #x36 #x3f #xf7 #xcc #x34 #xa5 #xe5 #xf1 #x71 #xd8 #x31 #x15
    #x04 #xc7 #x23 #xc3 #x18 #x96 #x05 #x9a #x07 #x12 #x80 #xe2 #xeb #x27 #xb2 #x75
    #x09 #x83 #x2c #x1a #x1b #x6e #x5a #xa0 #x52 #x3b #xd6 #xb3 #x29 #xe3 #x2f #x84
    #x53 #xd1 #x00 #xed #x20 #xfc #xb1 #x5b #x6a #xcb #xbe #x39 #x4a #x4c #x58 #xcf
    #xd0 #xef #xaa #xfb #x43 #x4d #x33 #x85 #x45 #xf9 #x02 #x7f #x50 #x3c #x9f #xa8
    #x51 #xa3 #x40 #x8f #x92 #x9d #x38 #xf5 #xbc #xb6 #xda #x21 #x10 #xff #xf3 #xd2
    #xcd #x0c #x13 #xec #x5f #x97 #x44 #x17 #xc4 #xa7 #x7e #x3d #x64 #x5d #x19 #x73
    #x60 #x81 #x4f #xdc #x22 #x2a #x90 #x88 #x46 #xee #xb8 #x14 #xde #x5e #x0b #xdb
    #xe0 #x32 #x3a #x0a #x49 #x06 #x24 #x5c #xc2 #xd3 #xac #x62 #x91 #x95 #xe4 #x79
    #xe7 #xc8 #x37 #x6d #x8d #xd5 #x4e #xa9 #x6c #x56 #xf4 #xea #x65 #x7a #xae #x08
    #xba #x78 #x25 #x2e #x1c #xa6 #xb4 #xc6 #xe8 #xdd #x74 #x1f #x4b #xbd #x8b #x8a
    #x70 #x3e #xb5 #x66 #x48 #x03 #xf6 #x0e #x61 #x35 #x57 #xb9 #x86 #xc1 #x1d #x9e
    #xe1 #xf8 #x98 #x11 #x69 #xd9 #x8e #x94 #x9b #x1e #x87 #xe9 #xce #x55 #x28 #xdf
    #x8c #xa1 #x89 #x0d #xbf #xe6 #x42 #x68 #x41 #x99 #x2d #x0f #xb0 #x54 #xbb #x16)
  "AES forward S-box (256 bytes).")

(defvar +aes-inv-sbox+
  #(#x52 #x09 #x6a #xd5 #x30 #x36 #xa5 #x38 #xbf #x40 #xa3 #x9e #x81 #xf3 #xd7 #xfb
    #x7c #xe3 #x39 #x82 #x9b #x2f #xff #x87 #x34 #x8e #x43 #x44 #xc4 #xde #xe9 #xcb
    #x54 #x7b #x94 #x32 #xa6 #xc2 #x23 #x3d #xee #x4c #x95 #x0b #x42 #xfa #xc3 #x4e
    #x08 #x2e #xa1 #x66 #x28 #xd9 #x24 #xb2 #x76 #x5b #xa2 #x49 #x6d #x8b #xd1 #x25
    #x72 #xf8 #xf6 #x64 #x86 #x68 #x98 #x16 #xd4 #xa4 #x5c #xcc #x5d #x65 #xb6 #x92
    #x6c #x70 #x48 #x50 #xfd #xed #xb9 #xda #x5e #x15 #x46 #x57 #xa7 #x8d #x9d #x84
    #x90 #xd8 #xab #x00 #x8c #xbc #xd3 #x0a #xf7 #xe4 #x58 #x05 #xb8 #xb3 #x45 #x06
    #xd0 #x2c #x1e #x8f #xca #x3f #x0f #x02 #xc1 #xaf #xbd #x03 #x01 #x13 #x8a #x6b
    #x3a #x91 #x11 #x41 #x4f #x67 #xdc #xea #x97 #xf2 #xcf #xce #xf0 #xb4 #xe6 #x73
    #x96 #xac #x74 #x22 #xe7 #xad #x35 #x85 #xe2 #xf9 #x37 #xe8 #x1c #x75 #xdf #x6e
    #x47 #xf1 #x1a #x71 #x1d #x29 #xc5 #x89 #x6f #xb7 #x62 #x0e #xaa #x18 #xbe #x1b
    #xfc #x56 #x3e #x4b #xc6 #xd2 #x79 #x20 #x9a #xdb #xc0 #xfe #x78 #xcd #x5a #xf4
    #x1f #xdd #xa8 #x33 #x88 #x07 #xc7 #x31 #xb1 #x12 #x10 #x59 #x27 #x80 #xec #x5f
    #x60 #x51 #x7f #xa9 #x19 #xb5 #x4a #x0d #x2d #xe5 #x7a #x9f #x93 #xc9 #x9c #xef
    #xa0 #xe0 #x3b #x4d #xae #x2a #xf5 #xb0 #xc8 #xeb #xbb #x3c #x83 #x53 #x99 #x61
    #x17 #x2b #x04 #x7e #xba #x77 #xd6 #x26 #xe1 #x69 #x14 #x63 #x55 #x21 #x0c #x7d)
  "AES inverse S-box (256 bytes).")

(defvar +aes-rcon+
  #(#x01 #x02 #x04 #x08 #x10 #x20 #x40 #x80 #x1b #x36)
  "AES round constants (10 values for AES-256).")

;;; ---------- Galois Field arithmetic ----------

(declaim (inline gf-mul))

(defun gf-mul (a b)
  "Multiply A and B in GF(2^8) with irreducible polynomial x^8+x^4+x^3+x+1.
Uses repeated doubling (no lookup tables)."
  (let ((result 0))
    (loop while (plusp b)
          do (when (oddp b)
               (setf result (logxor result a)))
             (setf a (let ((doubled (ash a 1)))
                       (if (>= doubled #x100)
                           (logxor doubled #x11b)
                           doubled)))
             (setf b (ash b -1)))
    result))

;;; ---------- GF(2^8) Lookup Tables for AES ----------
;;; Precomputed multiplication tables for constants used in MixColumns.
;;; Generated by evaluating (gf-mul constant x) for x = 0..255.

(defun %build-gf-table (constant)
  "Build a 256-element lookup table for GF(2^8) multiplication by CONSTANT."
  (let ((table (make-array 256 :element-type '(unsigned-byte 8))))
    (loop for i from 0 below 256
          do (setf (aref table i) (gf-mul constant i)))
    table))

(defvar +gf-mul-2+ (%build-gf-table 2)
  "Precomputed GF(2^8) multiplication by 2.")
(defvar +gf-mul-3+ (%build-gf-table 3)
  "Precomputed GF(2^8) multiplication by 3.")
(defvar +gf-mul-9+ (%build-gf-table 9)
  "Precomputed GF(2^8) multiplication by 9.")
(defvar +gf-mul-11+ (%build-gf-table 11)
  "Precomputed GF(2^8) multiplication by 11.")
(defvar +gf-mul-13+ (%build-gf-table 13)
  "Precomputed GF(2^8) multiplication by 13.")
(defvar +gf-mul-14+ (%build-gf-table 14)
  "Precomputed GF(2^8) multiplication by 14.")

;;; ---------- AES State Operations ----------
;;; State is a 16-byte octet vector in column-major order:
;;;   state[row + 4*col] = byte at (row, col)

(declaim (inline aes-sub-bytes aes-inv-sub-bytes))

(defun aes-sub-bytes (state)
  "Apply S-box substitution to each byte of STATE."
  (loop for i from 0 below 16
        do (setf (aref state i) (aref +aes-sbox+ (aref state i))))
  state)

(defun aes-inv-sub-bytes (state)
  "Apply inverse S-box substitution to each byte of STATE."
  (loop for i from 0 below 16
        do (setf (aref state i) (aref +aes-inv-sbox+ (aref state i))))
  state)

(defun aes-shift-rows (state)
  "Cyclic left-shift each row: row 0 by 0, row 1 by 1, row 2 by 2, row 3 by 3.
Column-major: state[row + 4*col]."
  ;; Row 1: shift left by 1
  (let ((t0 (aref state 1)))
    (setf (aref state 1)  (aref state 5))
    (setf (aref state 5)  (aref state 9))
    (setf (aref state 9)  (aref state 13))
    (setf (aref state 13) t0))
  ;; Row 2: shift left by 2
  (let ((t0 (aref state 2)) (t1 (aref state 6)))
    (setf (aref state 2)  (aref state 10))
    (setf (aref state 6)  (aref state 14))
    (setf (aref state 10) t0)
    (setf (aref state 14) t1))
  ;; Row 3: shift left by 3 (= right by 1)
  (let ((t0 (aref state 15)))
    (setf (aref state 15) (aref state 11))
    (setf (aref state 11) (aref state 7))
    (setf (aref state 7)  (aref state 3))
    (setf (aref state 3)  t0))
  state)

(defun aes-inv-shift-rows (state)
  "Inverse cyclic shift: row 1 right by 1, row 2 right by 2, row 3 right by 3."
  ;; Row 1: shift right by 1
  (let ((t0 (aref state 13)))
    (setf (aref state 13) (aref state 9))
    (setf (aref state 9)  (aref state 5))
    (setf (aref state 5)  (aref state 1))
    (setf (aref state 1)  t0))
  ;; Row 2: shift right by 2
  (let ((t0 (aref state 10)) (t1 (aref state 14)))
    (setf (aref state 10) (aref state 2))
    (setf (aref state 14) (aref state 6))
    (setf (aref state 2)  t0)
    (setf (aref state 6)  t1))
  ;; Row 3: shift right by 3 (= left by 1)
  (let ((t0 (aref state 3)))
    (setf (aref state 3)  (aref state 7))
    (setf (aref state 7)  (aref state 11))
    (setf (aref state 11) (aref state 15))
    (setf (aref state 15) t0))
  state)

(defun aes-mix-columns (state)
  "MixColumns: matrix multiply each column in GF(2^8).
Matrix: [[2,3,1,1],[1,2,3,1],[1,1,2,3],[3,1,1,2]]
Uses precomputed lookup tables for performance."
  (loop for c from 0 below 4
        for base = (* c 4)
        for s0 = (aref state base)
        for s1 = (aref state (+ base 1))
        for s2 = (aref state (+ base 2))
        for s3 = (aref state (+ base 3))
        do (setf (aref state base)
                 (logxor (aref +gf-mul-2+ s0) (aref +gf-mul-3+ s1) s2 s3))
           (setf (aref state (+ base 1))
                 (logxor s0 (aref +gf-mul-2+ s1) (aref +gf-mul-3+ s2) s3))
           (setf (aref state (+ base 2))
                 (logxor s0 s1 (aref +gf-mul-2+ s2) (aref +gf-mul-3+ s3)))
           (setf (aref state (+ base 3))
                 (logxor (aref +gf-mul-3+ s0) s1 s2 (aref +gf-mul-2+ s3))))
  state)

(defun aes-inv-mix-columns (state)
  "InvMixColumns: matrix multiply each column in GF(2^8).
Matrix: [[14,11,13,9],[9,14,11,13],[13,9,14,11],[11,13,9,14]]
Uses precomputed lookup tables for performance."
  (loop for c from 0 below 4
        for base = (* c 4)
        for s0 = (aref state base)
        for s1 = (aref state (+ base 1))
        for s2 = (aref state (+ base 2))
        for s3 = (aref state (+ base 3))
        do (setf (aref state base)
                 (logxor (aref +gf-mul-14+ s0) (aref +gf-mul-11+ s1)
                         (aref +gf-mul-13+ s2) (aref +gf-mul-9+ s3)))
           (setf (aref state (+ base 1))
                 (logxor (aref +gf-mul-9+ s0) (aref +gf-mul-14+ s1)
                         (aref +gf-mul-11+ s2) (aref +gf-mul-13+ s3)))
           (setf (aref state (+ base 2))
                 (logxor (aref +gf-mul-13+ s0) (aref +gf-mul-9+ s1)
                         (aref +gf-mul-14+ s2) (aref +gf-mul-11+ s3)))
           (setf (aref state (+ base 3))
                 (logxor (aref +gf-mul-11+ s0) (aref +gf-mul-13+ s1)
                         (aref +gf-mul-9+ s2) (aref +gf-mul-14+ s3))))
  state)

(defun aes-add-round-key (state expanded-key round)
  "XOR state with the round key from EXPANDED-KEY at ROUND."
  (let ((offset (* round 16)))
    (loop for i from 0 below 16
          do (setf (aref state i)
                   (logxor (aref state i)
                           (aref expanded-key (+ offset i))))))
  state)

;;; ---------- Key Expansion ----------

(defun aes-key-expansion (key)
  "Expand a 32-byte AES-256 key into 240 bytes (15 round keys).
KEY is a 32-byte octet vector. Returns a 240-byte octet vector."
  (let* ((nk 8)        ; key words (32-bit) for AES-256
         (nr 14)       ; number of rounds
         (nb 4)        ; block words
         (total-words (* nb (1+ nr)))  ; 60 words = 240 bytes
         (w (make-array (* total-words 4) :element-type '(unsigned-byte 8))))
    ;; Copy original key into first 8 words
    (replace w key :end2 32)
    ;; Expand
    (loop for i from nk below total-words
          for offset = (* i 4)
          for prev-offset = (* (1- i) 4)
          for nk-back-offset = (* (- i nk) 4)
          do (let ((temp (make-array 4 :element-type '(unsigned-byte 8))))
               ;; Copy w[i-1]
               (loop for j from 0 below 4
                     do (setf (aref temp j) (aref w (+ prev-offset j))))
               (cond
                 ;; Every nk-th word: RotWord + SubWord + Rcon
                 ((zerop (mod i nk))
                  (let ((t0 (aref temp 0)))
                    ;; RotWord: rotate left by 1 byte
                    (setf (aref temp 0) (aref temp 1))
                    (setf (aref temp 1) (aref temp 2))
                    (setf (aref temp 2) (aref temp 3))
                    (setf (aref temp 3) t0))
                  ;; SubWord
                  (loop for j from 0 below 4
                        do (setf (aref temp j) (aref +aes-sbox+ (aref temp j))))
                  ;; XOR with Rcon
                  (setf (aref temp 0)
                        (logxor (aref temp 0) (aref +aes-rcon+ (1- (/ i nk))))))
                 ;; AES-256 extra: SubWord at nk/2 position
                 ((and (> nk 6) (= (mod i nk) 4))
                  (loop for j from 0 below 4
                        do (setf (aref temp j) (aref +aes-sbox+ (aref temp j))))))
               ;; w[i] = w[i-nk] XOR temp
               (loop for j from 0 below 4
                     do (setf (aref w (+ offset j))
                              (logxor (aref w (+ nk-back-offset j))
                                      (aref temp j))))))
    w))

;;; ---------- Single Block Encrypt/Decrypt ----------

(defun aes-256-encrypt-block (block key)
  "Encrypt a single 16-byte BLOCK with AES-256.
KEY is 32 bytes (raw) or 240 bytes (pre-expanded).
Returns a new 16-byte octet vector."
  (let ((state (make-array 16 :element-type '(unsigned-byte 8)))
        (expanded-key (if (= (length key) 240) key (aes-key-expansion key))))
    ;; Copy input to state (column-major = same byte order for AES)
    (replace state block)
    ;; Initial round key addition
    (aes-add-round-key state expanded-key 0)
    ;; Rounds 1..13
    (loop for round from 1 to 13
          do (aes-sub-bytes state)
             (aes-shift-rows state)
             (aes-mix-columns state)
             (aes-add-round-key state expanded-key round))
    ;; Final round (no MixColumns)
    (aes-sub-bytes state)
    (aes-shift-rows state)
    (aes-add-round-key state expanded-key 14)
    state))

(defun aes-256-decrypt-block (block key)
  "Decrypt a single 16-byte BLOCK with AES-256.
KEY is 32 bytes (raw) or 240 bytes (pre-expanded).
Returns a new 16-byte octet vector."
  (let ((state (make-array 16 :element-type '(unsigned-byte 8)))
        (expanded-key (if (= (length key) 240) key (aes-key-expansion key))))
    (replace state block)
    ;; Initial round key addition (round 14)
    (aes-add-round-key state expanded-key 14)
    ;; Rounds 13..1
    (loop for round from 13 downto 1
          do (aes-inv-shift-rows state)
             (aes-inv-sub-bytes state)
             (aes-add-round-key state expanded-key round)
             (aes-inv-mix-columns state))
    ;; Final round (no InvMixColumns)
    (aes-inv-shift-rows state)
    (aes-inv-sub-bytes state)
    (aes-add-round-key state expanded-key 0)
    state))

;;; ---------- PKCS7 Padding ----------

(defun pkcs7-pad (data block-size)
  "Pad DATA with PKCS7 padding to a multiple of BLOCK-SIZE.
Always adds at least 1 byte of padding."
  (let* ((data-octets (ensure-octets data))
         (pad-len (- block-size (mod (length data-octets) block-size)))
         (result (make-array (+ (length data-octets) pad-len)
                             :element-type '(unsigned-byte 8))))
    (replace result data-octets)
    (loop for i from (length data-octets) below (length result)
          do (setf (aref result i) pad-len))
    result))

(defun pkcs7-unpad (data)
  "Remove PKCS7 padding from DATA. Validates padding bytes in constant time.
Signals error on invalid padding."
  (let* ((len (length data))
         (pad-byte (aref data (1- len)))
         (valid 1))  ; 1 = valid, 0 = invalid
    ;; Check pad-byte range: must be 1..16
    (when (or (zerop pad-byte) (> pad-byte 16) (> pad-byte len))
      (setf valid 0))
    ;; Check ALL padding bytes (constant-time: don't short-circuit)
    (let ((check-len (if (zerop pad-byte) 1 (min pad-byte len))))
      (loop for i from (- len check-len) below len
            do (setf valid (logand valid
                                   (if (= (aref data i) pad-byte) 1 0)))))
    (when (zerop valid)
      (error "Invalid PKCS7 padding"))
    (subseq data 0 (- len pad-byte))))

;;; ---------- AES-256-CBC Mode ----------

(defun aes-256-cbc-encrypt (plaintext key &key iv)
  "Encrypt PLAINTEXT with AES-256-CBC using KEY (32-byte octet vector).
IV defaults to 16 random bytes. Prepends IV to ciphertext.
PLAINTEXT can be a string or octet vector.
Returns (values ciphertext iv) where ciphertext includes the prepended IV."
  (let* ((plain-octets (pkcs7-pad (ensure-octets plaintext) 16))
         (actual-iv (or iv (secure-random-bytes 16)))
         (num-blocks (/ (length plain-octets) 16))
         (ciphertext (make-array (+ 16 (length plain-octets))
                                 :element-type '(unsigned-byte 8)))
         (prev-block (make-array 16 :element-type '(unsigned-byte 8)))
         (expanded-key (aes-key-expansion key)))
    ;; Prepend IV
    (replace ciphertext actual-iv)
    ;; Initialize prev-block with IV
    (replace prev-block actual-iv)
    ;; Encrypt each block
    (loop for b from 0 below num-blocks
          for in-offset = (* b 16)
          for out-offset = (+ 16 (* b 16))
          do ;; XOR plaintext block with previous ciphertext block (or IV)
             (let ((xored (make-array 16 :element-type '(unsigned-byte 8))))
               (loop for i from 0 below 16
                     do (setf (aref xored i)
                              (logxor (aref plain-octets (+ in-offset i))
                                      (aref prev-block i))))
               (let ((encrypted (aes-256-encrypt-block xored expanded-key)))
                 (replace ciphertext encrypted :start1 out-offset)
                 (replace prev-block encrypted))))
    (values ciphertext actual-iv)))

(defun aes-256-cbc-decrypt (ciphertext key &key iv)
  "Decrypt CIPHERTEXT with AES-256-CBC using KEY (32-byte octet vector).
If IV is not provided, extracts it from the first 16 bytes of CIPHERTEXT.
Returns plaintext as an octet vector (PKCS7 padding removed)."
  (let* ((actual-iv (or iv (subseq ciphertext 0 16)))
         (cipher-start (if iv 0 16))
         (cipher-data (subseq ciphertext cipher-start))
         (num-blocks (/ (length cipher-data) 16))
         (plaintext (make-array (length cipher-data) :element-type '(unsigned-byte 8)))
         (prev-block (make-array 16 :element-type '(unsigned-byte 8)))
         (expanded-key (aes-key-expansion key)))
    (replace prev-block actual-iv)
    ;; Decrypt each block
    (loop for b from 0 below num-blocks
          for offset = (* b 16)
          do (let* ((cipher-block (subseq cipher-data offset (+ offset 16)))
                    (decrypted (aes-256-decrypt-block cipher-block expanded-key)))
               ;; XOR with previous ciphertext block (or IV)
               (loop for i from 0 below 16
                     do (setf (aref plaintext (+ offset i))
                              (logxor (aref decrypted i)
                                      (aref prev-block i))))
               (replace prev-block cipher-block)))
    (pkcs7-unpad plaintext)))
